server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    location /md_viewer/ {
        try_files $uri $uri/ /md_viewer/index.html;
    }

    location = /md_viewer {
        return 301 /md_viewer/;
    }
}
